### ISSUE TITLE
WooCommerce Intercom Pro v161124.6961-RC (Release Candidate)

### ISSUE THREAD

**Issue by raamdev** [websharks/woocommerce-intercom-pro#30]
### Downloads

- [WooCommerce Intercom Pro v161124.6961-RC](https://github.com/websharks/woocommerce-intercom-pro/releases/tag/untagged-f8d189094309be135fe7) (requires membership in WebSharks organization on GitHub)

### Changelog

- See [WooCommerce Intercom Pro v161124.6961-RC](https://github.com/websharks/woocommerce-intercom-pro/releases/tag/untagged-f8d189094309be135fe7) (requires membership in WebSharks organization on GitHub)

### Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

_None at this time._

**Comment by renzms** [comment]
### Confirmed Working

- [x] Bug Fix: Call to undefined method WC_Order::get_currency() should be get_order_currency().  See Issue #4.
- [x] Bug Fix: In the Event API calls, amount must be given in cents (i.e., total x 100) for proper calculation on the Intercom side. See Issue #17.
- [x] New Feature: Adding support for URI Inclusion patterns. See Issue #12.
- [x] New Feature: Adding support for URI Exclusion patterns. See Issue #12.
- [x] Enhancement: Adding wp_site and wp_uri fields to JS Snippet to make it easier for support representatives to identify the origin of a customer request; e.g., whenever a single Intercom account is being used to support more then one WordPress installation, or multiple child sites/domains in a Multisite Network. See Issue #22.
- [x] Compatibility: Deprecating API Key setting for Intercom in favor of a Personal Access Token. There is now a configuration field under: WP Dashboard → WooCommerce → Intercom settings where you can supply a Personal Access Token for API calls to Intercom. Use the instructions provided in this area to generate and fill-in your Personal Access Token. Note: If you were previously using an Intercom API Key, it will continue to work, for now; but please provide a Personal Access Token to avoid problems in future releases of this plugin. See Issue #20.
- [x] Cleanup: Moving JS snippet into a template file w/ replacement code. See Issue #8.
- [x] Enhancement: Standardizing Event names sent to Intercom. New format: order-[status]. See Issue #19.
- [x] Compatibility: This release adds support for all WooCommerce Order and/or Subscription status changes, including those added by WooCommerce extensions such as the WooCommerce Give Order extension. See Issue #1. and Issue #19.

- [x] Enhancement: Adding support for guest checkout events that track a customer by email address instead of by user ID. See Issue #6.

- [x] Compatibility: This release adds compatibility with WooCommerce Subscriptions. See Issue #1.

**Comment by renzms** [comment]
@raamdev 

### Bug Found

When signing up for the first time and creating an account at checkout the following error prompt appears:

![screen shot 2016-11-28 at 8 50 40 pm](https://cloud.githubusercontent.com/assets/13220018/20669143/7e09c602-b5ad-11e6-9c7c-2d90d3952d50.png)


Tested using:
- **WP Sharks Core Version 161026.47592**
- **WooCommerce Intercom Pro Version 161124.6961-RC**
- **WooCommerce Version 2.6.8**

### Steps to reproduce

- Setup WooCommerce and test products
- Purchase test product as a logged-out visitor
- Sign up and create a new account at checkout
- The following page shows the error:

```
Client error: `POST https://api.intercom.io/events` resulted in a `404 Not Found` response: {"type":"error.list","request_id":"aolc376cuogshlk6422g","errors":[{"code":"not_found","message":"User Not Found"}]}
```

Please note however, that the account creation and the order is still taken successfully despite the error if you visit the My Account page.

![screen shot 2016-11-28 at 9 04 55 pm](https://cloud.githubusercontent.com/assets/13220018/20669295/69cddd1c-b5ae-11e6-95e0-87d606898871.png)

![screen shot 2016-11-28 at 9 04 47 pm](https://cloud.githubusercontent.com/assets/13220018/20669297/6ed2da38-b5ae-11e6-8c3f-8bf99078b329.png)

**Comment by renzms** [comment]
@raamdev Bug regarding New account signup has been fixed, please see [Issue #6](https://github.com/websharks/woocommerce-intercom-pro/issues/6#issuecomment-264646916)

**Comment by raamdev** [comment]
@renzms Thank you.

I'll be publishing an official WooCommerce Intercom Pro release shorlty.

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#30).
